enableFeaturePreview("GRADLE_METADATA")

include("scrimage-core")
include("scrimage-tests")
include("scrimage-filters")
include("scrimage-benchmarks")
include("scrimage-formats-extra")
include("scrimage-webp")
include("scrimage-scala_2.12")
include("scrimage-scala_2.13")
include("scrimage-examples")
